name: Build API

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore packages
        run: dotnet restore src/Api

      - name: Build
        run: dotnet build src/Api --no-restore --configuration Release